### PR TITLE
Feature/bosc talk

### PR DESCRIPTION
**Pull request by pbelmann**
first version

### CODE REVIEW

**Comment by michaelbarton** [comment]
Thanks for creating the talk and being will to present at BOSC Peter. My
suggestion would be to simplify the talk and remove a lot of the content. I
believe from looking at the agenda you will be in a session where everyone is
presenting a short 5 minute talk. Therefore amongst a list of speakers you want
to keep your message short as possible and just limit it to a couple of points.
Think in terms of "What single point do I want someone to take away from what
I'm presenting?" I would aim for a very high level overview of what the problem
is and how bioboxes aims to solve it.

My suggestions for the appearance
- I suggest using same font and colour as the website. This will add a
  consistent feel since you already have the logo. You could even use the
  bold version for emphasis, similarly to the logo text.
- If you can, remove the date and background from all slides (unless it is an
  insitutational requirement). This will focus content on the main point of
  each slide.
- I encourage you to remove the bullet points - with 5 minutes you have very
  little time so keeping each slide to just one point may help get your
  message across.

Specific points:
- I think your name on the front slide alone is fine. I believe this is
  usually the case that only the presenter is listed. You could add your
  twitter handle.
- I think simplify the second (motivation) slide. Instead I suggest focusing
  on the current problem in bioinformatics software - much of it is broken,
  hard to use or install.
- I would definitely drop the yaml slide as it is too much detail. If anyone
  is interested they can go to the website for find out more information.
- Drop community driven slide - again I think this information can be found
  from the website.
- Last slide - just have the URL and twitter account. However add your poster
  number if you have it so anyone can find you later at BOSC.
- The Docker slide is a good idea however given the time available try to
  present a very high level overview. Assume a very broad range of knowledge
  in the audience - consider how you would explain what Docker is to someone
  you know who doesn't work in computing and that is probably a good
  approximation.
- The 4th slide I think is the best because this explains what bioboxes is. I
  would focus the talk around this. Clarify this to get the message across -
  how bioboxes works and how it can help people in their work. My suggestion
  would be something like focusing and simplifying the concept you have of
  boxes that take inputs and generate outputs.

I can take a look again tomorrow if it would be helpful.

**Comment by bgruening** [comment]
Just to let you know this talk was great!!!

**Comment by bgruening** [comment]
:+1:

**Comment by pbelmann** [comment]
thank you Björn

**Pull request merged**
